// <auto-generated />
using System;
using ArthyFoundation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArthyFoundation.Migrations
{
    [DbContext(typeof(ArthyDbContext))]
    partial class ArthyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("ArthyFoundation.Models.DonationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ContributedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DonorEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DonorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProofDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProofImageName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedCause")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Donations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 3000.00m,
                            ContributedAt = new DateTime(2026, 8, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            DonorEmail = "amit.sharma@example.com",
                            DonorName = "Amit Sharma",
                            IsVerified = true,
                            ProofDescription = "Rural Girls Education Kit & Uniform Distribution in West Tambaram",
                            ProofImageName = "shiksha-education.jpg",
                            SelectedCause = "Child Education Support",
                            TransactionId = "TXN101"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1000.00m,
                            ContributedAt = new DateTime(2026, 8, 28, 14, 30, 0, 0, DateTimeKind.Utc),
                            DonorEmail = "sneha.k@example.com",
                            DonorName = "Sneha Krishnan",
                            IsVerified = true,
                            ProofDescription = "V.P. Silver grocery bag distribution to local single parent nomad camps",
                            ProofImageName = "aahar-hunger.jpg",
                            SelectedCause = "Grassroots Grocery & Grain Seva",
                            TransactionId = "TXN102"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 4000.00m,
                            ContributedAt = new DateTime(2026, 9, 1, 11, 15, 0, 0, DateTimeKind.Utc),
                            DonorEmail = "ravi.kumar@example.com",
                            DonorName = "Ravi Kumar",
                            IsVerified = true,
                            ProofDescription = "Heavy duty yellow waterproof tarps & bed mats handed over for monsoon shelter support",
                            ProofImageName = "sahaara-shelter.jpg",
                            SelectedCause = "Waterproof Shelter & Tarps",
                            TransactionId = "TXN103"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 5000.00m,
                            ContributedAt = new DateTime(2026, 9, 3, 16, 45, 0, 0, DateTimeKind.Utc),
                            DonorEmail = "rajesh.g@example.com",
                            DonorName = "Rajesh G",
                            IsVerified = true,
                            ProofDescription = "Community food and basic amenities distribution camp inside tribal settlements",
                            ProofImageName = "jeevitha-community.jpg",
                            SelectedCause = "Tribal Community Development",
                            TransactionId = "TXN104"
                        });
                });

            modelBuilder.Entity("ArthyFoundation.Models.Inquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Inquiries");
                });
#pragma warning restore 612, 618
        }
    }
}
